// export const PUBLIC_URL = process.env.PUBLIC_URL;
// export const MAXWIDTH = "1328px";

export const LOGIN_SUCCESS_MSG = "Thank you, User registration successfully completed";
export const COMMON_ERROR_MSG = "Something went wrong";

export const LOGIN_DISPLAY_MSG = "Login to view Heatmap";
export const months = [
    'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
    'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'
];
export const SUBSCRIBE_MSG = "Please Subscribe to View all Indices";
export const SUBSCRIBE_Success_MSG = "Subscription Under Devlopment";
// export const SUBSCRIBE_Success_MSG = "Subscription Successful";

export const Broad_Compare_msg = "Displaying All Broad Stocks";
export const Strategy_Compare_msg = "Displaying All Strategy Stocks";
export const Thematic_Compare_msg = "Displaying All Thematic Stocks";
export const Sector_Compare_msg = "Displaying All Sector Stocks";
export const All_Compare_msg = "Displaying All Stocks";

export const graph5names = [
    "GNFT50",
    "GNFTMC50",
    "GNFTSC50",
    "GNFTLMC250",
    "GNFTBANK",
];

export const graph113names = [
    "GNFTN50",
    "GNFT100",
    "GNFT200",
    "GNFTTTLMAR",
    "GNFT500",
    "GNFT500MC50_25_25",
    "GNFT500LGMSEQLCAPWTD",
    "GNFT50",
    "GNFTMC150",
    "GNFTMC50",
    "GNFTMCSEL",
    "GNFTMC100",
    "GNFTSC250",
    "GNFTSC50",
    "GNFTFSC100",
    "GNFTMC250",
    "GNFTLMC250",
    "GNFTMSC400",
    "GNFT100EQLWGT",
    "GNFT100LVLT30",
    "GNFT50A",
    "GNFT50FPR",
    "GNFT50FTR",
    "GNFT200MOM30",
    "GNFT200AL30",
    "GNFT100AL30",
    "GNFTAL50",
    "GNFTALVLT30",
    "GNFTAQLTLVLT30",
    "GNFTAQLTVLLVLT30",
    "GNFTDO50",
    "GNFTGRTHSEC15",
    "GNFTHBETA50",
    "GNFTLVLT50",
    "GNFTT10EQLWGT",
    "GNFT100QLT30",
    "GNFTMC150MOM50",
    "GNFT500MOM50",
    "GNFTMC150QLT50",
    "GNFTSC250QLT50",
    "GNFTMSC400MOMQLT100",
    "GNFTSC250MOMQLT100",
    "GNFTQLTLVLT30",
    "GNFT50DIVPNT",
    "GNFT50EW",
    "GNFT50PR1XINVS",
    "GNFT50PR2XLVG",
    "GNFT50TR1XINVS",
    "GNFT50TR2XLVG",
    "GNFT50VL20",
    "GNFT200VL30",
    "GNFT500VL50",
    "GNFT500EQLWGT",
    "GNFT200QLT30",
    "GNFT50SRTDURDEBTDYNP_B",
    "GNFT50SRTDURDEBTDYNP_E",
    "GNFTEQTSAV",
    "GNFTCORPGRPIABG",
    "GNFTCOMM",
    "GNFTCH",
    "GNFTCPSE",
    "GNFTENG",
    "GNFTEVNAAMT",
    "GNFTHOUS",
    "GNFT100ESG",
    "GNFT100EESG",
    "GNFT100ESGSL",
    "GNFTCONS",
    "GNFTINDCONS",
    "GNFTINDDIG",
    "GNFTINDMFG",
    "GNFTINDTR",
    "GNFTINFS",
    "GNFTINDCORPGRPIMG",
    "GNFTMCL15",
    "GNFTMSINDCON",
    "GNFTMNC",
    "GNFTMOB",
    "GNFTPSE",
    "GNFTRI",
    "GNFTNCC",
    "GNFTSERSEC",
    "GNFTSH25",
    "GNFTINDCORPGRPITG",
    "GNFTINDCORPGRPITG25PC",
    "GNFTTRANSLOG",
    "GNFT100L15",
    "GNFT50SH",
    "GNFT500SH",
    "GNFT500MULCINDMFG50_30_20",
    "GNFT500MULCINFS50_30_20",
    "GNFTSMEEMG",
    "GNFTAUTO",
    "GNFTBANK",
    "GNFTFINSERV",
    "GNFTFINSERV25_50",
    "GNFTFINSERVEB",
    "GNFTFMCG",
    "GNFTHLTC",
    "GNFTIT",
    "GNFTMEDIA",
    "GNFTMETAL",
    "GNFTPHARMA",
    "GNFTPVTB",
    "GNFTPSUB",
    "GNFTREAL",
    "GNFTCD",
    "GNFTOG",
    "GNFTMSFS",
    "GNFTMSHC",
    "GNFTMSITTEL",
    "GNFT50USD",
    "GNFTVIX",]